### ISSUE TITLE
MSI: VS updates

### ISSUE THREAD

**Issue by true-while** [mspremier/AzureFastStartForIoT#12]
1. Surprisingly found out that code is based on “Anniversary Edition”. Which is make me to install Update 3 on my VS 2015. It is not big deal but consume 1.5 hours of installation.
 
![2](https://cloud.githubusercontent.com/assets/25492227/22528481/7442444c-e8a1-11e6-8c1a-5210fd21f59b.png)

Then I got a everything installed my code does not compiled because can no find following namespaces. 

```
using Windows.Devices.Gpio;
using Windows.Devices.Spi; 
```

In addition, I had to connect “Windows IOT Extension for UWP” in references. 
It is better to mentioned it in advance.

2. Finally when I have all compiled my code has been successfully deployed but can not be run and fail with strange error “Exception thrown: 'System.TypeLoadException'” 
My issue solved in the following post http://stackoverflow.com/questions/38812045/windows-10-iot-14393-sdk-windows-devices-gpio-bug
It made me reinstall the SDK which is come up with VS Update I guess.

**Comment by UKNorthernlad** [comment]
The requirement for VS 2015 Update 3 is detailed already here: https://github.com/mspremier/AzureFastStartForIoT/blob/master/IoT%20Developer%20Setup.docx

If you find this problem occurs on a freshly installed machine with VS 2015 U3, open this issue again and we'll investigate.
