### ISSUE TITLE
MSI: Tag id 000000

### ISSUE THREAD

**Issue by true-while** [mspremier/AzureFastStartForIoT#14]
During the test when I removed tag quickly the reading was not completed.  I got the tag id “00000000”. I believe that is need to be fixed by additional check before upload data in Azure.
![2](https://cloud.githubusercontent.com/assets/25492227/22528616/11e04712-e8a2-11e6-88a9-8e52b772269d.png)

**Comment by UKNorthernlad** [comment]
Added check to only send message when RFiD != "00000000"
