### ISSUE TITLE
MSI: Format README.md

### ISSUE THREAD

**Issue by true-while** [mspremier/AzureFastStartForIoT#16]
1. You have numbering list on the pictures as well.  
2. Step 7 & Step 6 lost numbers in the middle and start over from 1.

**Comment by UKNorthernlad** [comment]
I used the auto numbering system in markdown however you don't seem to be able to control when numbering restarts. I had to put numbers on the pictures else the numbers underneath them kept resetting back to 1. A right royal pain.

To solve it I think we'll have to just number each item manually as they do here for example - https://raw.githubusercontent.com/Microsoft/iot-workshops/master/IoTHub-TwinsRoutingMethods/README.md

**Comment by UKNorthernlad** [comment]
Formatting all updated now.
