### ISSUE TITLE
Connected Campus requrements

### ISSUE THREAD

**Issue by true-while** [mspremier/AzureFastStartForIoT#18]
> Adafruit BMP28 Barometric Pressure & Altitude Sensor  

We have another sensor BM**E**28 in Kit:

> •2 x Potentiometer - 10K

The schema provide images of the 3 pin switches, not potentiometers. 

> •Resistor 10k ohm
> •Resistor 560 ohm

I found 4  (two 10K ohm and two 220 ohm) on circuit diagram. What is right?

**Comment by true-while** [comment]
BTW  560 ohm resistor works much better with provided LED.

**Comment by UKNorthernlad** [comment]
The BM**E**280 is an updated version of the BM**P**280 chip which has the added ability to read humidity over and above pressure and temperature.

See the following if you are interested: 

BME280: https://learn.adafruit.com/adafruit-bme280-humidity-barometric-pressure-temperature-sensor-breakout/wiring-and-test?view=all

BMP280: https://learn.adafruit.com/adafruit-bmp280-barometric-pressure-plus-temperature-sensor-breakout/overview?view=all

The pin-outs on both these boards are the same, they can be used interchangeably (as we don't read humidity in the Connected Campus scenario).

I will therefore update the documentation to refer to the BME280 so as to eliminate any confusion.

**Comment by UKNorthernlad** [comment]
Documentation around BME/BMP 280 confusion now added.

**Comment by UKNorthernlad** [comment]
I'm not sure what you mean by 

> The schema provide images of the 3 pin switches, not potentiometers.

Are you referring to this bit of the Fitzing diagram:

![pots](https://cloud.githubusercontent.com/assets/6067510/23219549/44438a72-f917-11e6-9a80-829a2f915ad7.png)

The image does show potentiometers, these are NOT switches.

**Comment by UKNorthernlad** [comment]
> I found 4 (two 10K ohm and two 220 ohm) on circuit diagram. What is right?

Yes you are correct. When I built the circuit myself I built it with the 560ohm resistor you suggested and it worked great. The diagram was taken from another website and is wrong - I will produce an update.

**Comment by true-while** [comment]
I have a comment about BME28 that is quite easy to add huminidy.
The changes is not so massive my customer is hospital and interested in huminidy as well.
I can share my updates, but there is no option to attach it :(

**Comment by true-while** [comment]
Disregard potentiometers questions. I saw that most of the project in https://www.hackster.io/ has the same outlook. Let's left this as is, just provide labels which one is for low light and bright light
