### ISSUE TITLE
ConnectedCampus IotHub config

### ISSUE THREAD

**Issue by true-while** [mspremier/AzureFastStartForIoT#19]
> 5.Finally you should also make a copy of the Event Hub-compatible name & Event Hub-compatible endpoint values. You'll need these later on when you start to read data back from IoT Hub.

The screen is significantly changed.
![1](https://cloud.githubusercontent.com/assets/25492227/23081012/06e3a896-f521-11e6-8d13-a56e0fcab202.png)

**Comment by UKNorthernlad** [comment]
I have updated the scenario with the image you have provided.

**Comment by true-while** [comment]
Thanks
