### ISSUE TITLE
Connected Campus: Project 

### ISSUE THREAD

**Issue by true-while** [mspremier/AzureFastStartForIoT#20]
> 1.Open Visual Studio then go File->Project->Visual C#->Windows->Windows IoT Core and select the Background Application (IoT) template.

the project you need to select come up from template. it is not "Blank App"
![newproj](https://cloud.githubusercontent.com/assets/25492227/23083677/ea21c150-f52c-11e6-9fc3-28a01fc6584d.png)
"

**Comment by UKNorthernlad** [comment]
I would say this was true IF we where building a UWP application that needed to run as a background task on the RPi. The example code here however provides for a GUI (I'm not talking about the WebServer Admin interface). Admittedly its a pretty crappy GUI that only shows the device name and IP address, but it's a GUI all the same. The "Background Application (IoT)" template you suggest does not allow for a GUI - as the name of the template suggests, its for background tasks only.

Perhaps in the future the example could be rewritten to remove the GUI however right now it's a whole load of work for zero benefit. Other scenarios are all written using the Backgroup Application (IoT) template so people can their fix there if they wish.

I won't therefore be taking this any further right now.

**Comment by true-while** [comment]
The issue not about which template we need to use. The issue is mismatching screen with the task.
Taks said : File->Project->Visual C#->Windows->Windows IoT Core and select the **Background Application (IoT) template.**
But on the screen it shown "Blank App"  - that is confusing.
