### ISSUE TITLE
GIT not in my path to execute

### ISSUE THREAD

**Issue by egotisticdrip76** [mspremier/AzureFastStartForIoT#3]
I was not able to use the command 'Git Clone' directly I used:
Source>"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git\git" clone https://github.com/UKNorthernlad/AzureFastStartForIoT.git

I'm not saying that this is something we need to fix, just a remark :-)

**Comment by UKNorthernlad** [comment]
The path you used is to the version of the Git tools downloaded by Visual Studio. I had the full separate tools from Github.com installed. 

We need to make this distinction in the lab guide and call out the github.com tools as a pre-req.

**Comment by UKNorthernlad** [comment]
Created before first release was ready.
