### ISSUE TITLE
MSI: Device1 – but it names MyFirstDevice on screen

### ISSUE THREAD

**Issue by true-while** [mspremier/AzureFastStartForIoT#8]
Device1 – but it names MyFirstDevice on screen. Should we user hardcoded device name in the code? Why not to move device’s name in settings?

Go to the Management tab and Click on the Create button. The Create Device popup will be displayed. Enter "**device1**" as the Device ID for your device and click on Create. The device name is important as other parts of the supplied sample program rely on this.

Or sync with Pi name? We can also use following code to identify the host name of Pi.
```
private string GetHostName()
{
            foreach (HostName name in NetworkInformation.GetHostNames())
            {
                if (HostNameType.DomainName == name.Type)
                {
                    return name.DisplayName;
                }
            }

            return "Unknown";
}
```

Later In the code, we have to hardcode device name. Why not to use Settings and concatenate connections string from values?  We can also create // TODO  item for it to easy find.
const string deviceConnectionString = "HostName=devhubb99.azure-devices.net;DeviceId=device1;SharedAccessKey=UShGPPPi5Td1vCzYGEvE0/ZiYUDlb2YwsmHOEG91pIs=";

**Comment by UKNorthernlad** [comment]
I agree, these would be useful changed. Why don't you correct them and send a pull request?
