### ISSUE TITLE
MSI: Screenshots of Device Explore

### ISSUE THREAD

**Issue by true-while** [mspremier/AzureFastStartForIoT#9]
The screenshots of Device Explore is not up to date. They come up with more fields which is confused.

**Comment by UKNorthernlad** [comment]
I only took the screen shots a month ago - such is the pace of change. Let me have a look, download the latest Device Explorer and take new screen shots.

**Comment by UKNorthernlad** [comment]
I've just installed the latest version of the Device Explorer tool (https://github.com/Azure/azure-iot-sdks/releases/download/2016-11-17/SetupDeviceExplorer.msi) but I don't see any more fields on the Configuration tab than what is shown in the screen shot. There is an extra tab at the top of the application called "Call Method on Device" but we don't use this. I don't see how a user could get confused. 

If you can convince me I will reopen the issue.
